// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaARgRmmhKXeXcLPMKs-UB3CQ5uRopEZQ',
    appId: '1:484134965272:web:5d2eaa64439d712ab6736d',
    messagingSenderId: '484134965272',
    projectId: 'flood-sense-5e569',
    authDomain: 'flood-sense-5e569.firebaseapp.com',
    storageBucket: 'flood-sense-5e569.firebasestorage.app',
    measurementId: 'G-FDLK6YZ4GJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgpVI2Ua23U10G2rWsdff24YE-JfEZfIo',
    appId: '1:484134965272:android:aad6a4b6cee95d73b6736d',
    messagingSenderId: '484134965272',
    projectId: 'flood-sense-5e569',
    storageBucket: 'flood-sense-5e569.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArTqQGNf5fDpEGIXBwrYWrEujm3AOOHU4',
    appId: '1:484134965272:ios:2aeceb8c63196789b6736d',
    messagingSenderId: '484134965272',
    projectId: 'flood-sense-5e569',
    storageBucket: 'flood-sense-5e569.firebasestorage.app',
    iosBundleId: 'com.example.floodsense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArTqQGNf5fDpEGIXBwrYWrEujm3AOOHU4',
    appId: '1:484134965272:ios:2aeceb8c63196789b6736d',
    messagingSenderId: '484134965272',
    projectId: 'flood-sense-5e569',
    storageBucket: 'flood-sense-5e569.firebasestorage.app',
    iosBundleId: 'com.example.floodsense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaARgRmmhKXeXcLPMKs-UB3CQ5uRopEZQ',
    appId: '1:484134965272:web:c1fcade35326e899b6736d',
    messagingSenderId: '484134965272',
    projectId: 'flood-sense-5e569',
    authDomain: 'flood-sense-5e569.firebaseapp.com',
    storageBucket: 'flood-sense-5e569.firebasestorage.app',
    measurementId: 'G-D1N2GZK9FF',
  );
}
